AWSTemplateFormatVersion: 2010-09-09
Description: "Creates lambda for calculating best random number and writing to database"
# TODO: Take in code zip as var, split policies for least privilage
Parameters:
  S3Key:
    Type: String
  Timeout:
    Type: String
  HandlerName:
    Type: String
  TableName:
    Type: String
  ReadCapacityUnits:
    Type: Number
  WriteCapacityUnits:
    Type: Number
  HashKeyElementName:
    Type: String
  HashKeyElementType:
    Type: String

Resources:
  RandomTollFreeGenLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: "randomTollFreeGen"
      Handler: !Ref HandlerName
      Role: !GetAtt RandomTollFreeGenRole.Arn
      Code:
        S3Bucket:
          Fn::ImportValue: !Sub "CodeBucketName-${AWS::AccountId}"
        S3Key:
          Ref: S3Key
      Runtime: "python3.8"
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Timeout: !Ref Timeout
      MemorySize: "128"

  RandomTollFreeGenRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: RandomTollFreeGenRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: RandomTollFreeGenPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents

                Resource: "*"
              - Effect: Allow
                Action:
                  - dynamodb:DescribeTable
                  - dynamodb:BatchWriteItem
                  - dynamodb:PutItem
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/rolodex"

  RolodexDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: !Ref "HashKeyElementName"
          AttributeType: !Ref "HashKeyElementType"
      KeySchema:
        - AttributeName: !Ref "HashKeyElementName"
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref "ReadCapacityUnits"
        WriteCapacityUnits: !Ref "WriteCapacityUnits"
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
